# Generated by Django 6.0.4 on 2026-04-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
    ]
